{{- $env := .Values.env -}}
{{- range .Values.modules }}
{{- if eq .source "chartRepo" }}
---
# infra module {{ .name }} -> Helm repo source
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.source.namespace }}
  labels:
    platform/module: {{ .name }}
    platform/env: {{ $env }}
    platform/managed-by: platformctl
spec:
  url: {{ .repoURL }}
  interval: 10m
{{- end }}
---
# infra module {{ .name }} -> HelmRelease in {{ .namespace }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.source.namespace }}
  labels:
    platform/module: {{ .name }}
    platform/env: {{ $env }}
    platform/managed-by: platformctl
spec:
  interval: 10m
  releaseName: {{ .name }}
  targetNamespace: {{ .namespace }}
  storageNamespace: {{ .namespace }}
  {{- include "cluster.remediation" . | nindent 2 }}
  chart:
    spec:
      {{- if eq .source "chartRepo" }}
      chart: {{ .chart }}
      version: {{ .version }}
      sourceRef:
        kind: HelmRepository
        name: {{ .name }}
        namespace: {{ $.Values.source.namespace }}
      {{- else }}
      chart: ./{{ .chart }}
      sourceRef:
        {{- include "cluster.gitSourceRef" $ | nindent 8 }}
      {{- end }}
      reconcileStrategy: Revision
  {{- if .values }}
  values:
    {{- toYaml .values | nindent 4 }}
  {{- end }}
{{- end }}
