// Package render turns a defaults-applied deploy.yaml (+ target env + CI image)
// into desired state: chart values matching charts/app/values.yaml, wrapped in a
// Flux HelmRelease that carries them inline. The render path does NOT write
// per-app files; the caller upserts the Result into the env umbrella values at
// clusters/<env>/platform.yaml via (*Result).ToAppEntry + UpsertApp (see
// internal/render/platform.go). Flux is the only writer to the cluster.
package render

import (
	"fmt"

	"github.com/jakenesler/idp/internal/appconfig"
	"github.com/jakenesler/idp/internal/clusterenv"
	"sigs.k8s.io/yaml"
)

// Result is the rendered desired state for one app in one env.
type Result struct {
	App         appconfig.App
	Env         string
	Values      Values
	HelmRelease HelmRelease
	// StoreReleases are the dedicated per-app data-store Flux HelmReleases (e.g.
	// the dev per-app Postgres) rendered alongside the app, each into its OWN
	// namespace. Empty in prod (external/managed stores).
	StoreReleases []StoreRelease
	// Connections is the resolved connectsTo set (for the plan summary).
	Connections []ResolvedConnection
	// SecretKeys is the canonical list of secret-backed env keys the app needs.
	SecretKeys []string
}

// Render produces the desired state for app in env. It applies defaults (the App
// must already be validated by the caller / policy), builds values, resolves
// connections, and wraps the values in a Flux HelmRelease. It does not write
// anything; the caller upserts the Result into the env umbrella via
// (*Result).ToAppEntry + UpsertApp (platform.go).
func Render(app appconfig.App, env string, c *clusterenv.Config, image, deployTime string) (*Result, error) {
	app.ApplyDefaults()

	values, err := BuildValues(app, env, c, image, deployTime)
	if err != nil {
		return nil, fmt.Errorf("build values: %w", err)
	}
	conns, err := ResolveConnections(app, env, c)
	if err != nil {
		return nil, fmt.Errorf("resolve connections: %w", err)
	}
	hr := BuildHelmRelease(app, env, c, values)
	stores := BuildStoreReleases(app, env, c)

	var secretKeys []string
	secretKeys = append(secretKeys, DataStoreEnvKeys(app)...)
	secretKeys = append(secretKeys, StorageEnvKeys(app)...)

	return &Result{
		App:           app,
		Env:           env,
		Values:        values,
		HelmRelease:   hr,
		StoreReleases: stores,
		Connections:   conns,
		SecretKeys:    secretKeys,
	}, nil
}

// HelmReleaseYAML serializes the Flux HelmRelease to deterministic YAML
// (sigs.k8s.io/yaml sorts map keys), with a generated-file header. Used by the
// `plan` command and the (best-effort) infra apply path for human-readable
// output; the umbrella render path carries the values inline instead.
func (r *Result) HelmReleaseYAML() ([]byte, error) {
	body, err := yaml.Marshal(r.HelmRelease)
	if err != nil {
		return nil, fmt.Errorf("marshal helmrelease: %w", err)
	}
	header := fmt.Sprintf(
		"# Generated by idpctl. DO NOT EDIT BY HAND.\n"+
			"# Source: deploy.yaml (app=%s) rendered for env=%s.\n"+
			"# Edit the app's deploy.yaml and re-run `idpctl render` instead.\n",
		r.App.App, r.Env,
	)
	return append([]byte(header), body...), nil
}
