// Package render turns a defaults-applied deploy.yaml (+ target env + CI image)
// into desired state: chart values matching charts/app/values.yaml, and a Flux
// HelmRelease that carries them inline. The renderer writes the HelmRelease to
// environments/<env>/apps/<app>.yaml; Flux is the only writer to the cluster.
package render

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/jakenesler/platformctl/internal/appconfig"
	"github.com/jakenesler/platformctl/internal/clusterenv"
	"sigs.k8s.io/yaml"
)

// Result is the rendered desired state for one app in one env.
type Result struct {
	App         appconfig.App
	Env         string
	Values      Values
	HelmRelease HelmRelease
	// StoreReleases are the dedicated per-app data-store Flux HelmReleases (e.g.
	// the dev per-app Postgres) rendered alongside the app, each into its OWN
	// namespace. Empty in prod (external/managed stores).
	StoreReleases []StoreRelease
	// Connections is the resolved connectsTo set (for the plan summary).
	Connections []ResolvedConnection
	// SecretKeys is the canonical list of secret-backed env keys the app needs.
	SecretKeys []string
}

// Render produces the desired state for app in env. It applies defaults (the App
// must already be validated by the caller / policy), builds values, resolves
// connections, and wraps the values in a Flux HelmRelease. It does not write
// anything; use WriteResult or RenderToFile for the write path.
func Render(app appconfig.App, env string, c *clusterenv.Config, image, deployTime string) (*Result, error) {
	app.ApplyDefaults()

	values, err := BuildValues(app, env, c, image, deployTime)
	if err != nil {
		return nil, fmt.Errorf("build values: %w", err)
	}
	conns, err := ResolveConnections(app, env, c)
	if err != nil {
		return nil, fmt.Errorf("resolve connections: %w", err)
	}
	hr := BuildHelmRelease(app, env, c, values)
	stores := BuildStoreReleases(app, env, c)

	var secretKeys []string
	secretKeys = append(secretKeys, DataStoreEnvKeys(app)...)
	secretKeys = append(secretKeys, StorageEnvKeys(app)...)

	return &Result{
		App:           app,
		Env:           env,
		Values:        values,
		HelmRelease:   hr,
		StoreReleases: stores,
		Connections:   conns,
		SecretKeys:    secretKeys,
	}, nil
}

// HelmReleaseYAML serializes the Flux HelmRelease to deterministic YAML
// (sigs.k8s.io/yaml sorts map keys), with a generated-file header.
func (r *Result) HelmReleaseYAML() ([]byte, error) {
	body, err := yaml.Marshal(r.HelmRelease)
	if err != nil {
		return nil, fmt.Errorf("marshal helmrelease: %w", err)
	}
	header := fmt.Sprintf(
		"# Generated by platformctl. DO NOT EDIT BY HAND.\n"+
			"# Source: deploy.yaml (app=%s) rendered for env=%s.\n"+
			"# Edit the app's deploy.yaml and re-run `platformctl render` instead.\n",
		r.App.App, r.Env,
	)
	return append([]byte(header), body...), nil
}

// ValuesYAML serializes just the chart values (useful for `plan`/debugging or a
// sibling values file).
func (r *Result) ValuesYAML() ([]byte, error) {
	return yaml.Marshal(r.Values)
}

// StoreReleaseYAML serializes one per-app data-store Flux HelmRelease to
// deterministic YAML with a generated-file header.
func (r *Result) StoreReleaseYAML(s StoreRelease) ([]byte, error) {
	body, err := yaml.Marshal(s.HelmRelease)
	if err != nil {
		return nil, fmt.Errorf("marshal store helmrelease: %w", err)
	}
	header := fmt.Sprintf(
		"# Generated by platformctl. DO NOT EDIT BY HAND.\n"+
			"# Per-app %s data store for app=%s, env=%s (namespace %s).\n"+
			"# Edit the app's deploy.yaml and re-run `platformctl render` instead.\n",
		s.Tool, r.App.App, r.Env, s.Namespace,
	)
	return append([]byte(header), body...), nil
}

// OutputPath is the canonical destination for the rendered HelmRelease relative
// to a platform repo root: environments/<env>/apps/<app>.yaml.
func OutputPath(root, env, app string) string {
	return filepath.Join(root, "environments", env, "apps", app+".yaml")
}

// WriteResult writes the rendered app HelmRelease to
// environments/<env>/apps/<app>.yaml under root AND every per-app data-store
// HelmRelease (e.g. the dev per-app Postgres) to
// environments/<env>/apps/<store>.yaml, creating directories as needed. It
// returns every path written (app first, then stores in render order). The
// FluxInstance Kustomization applies the whole environments/<env> tree, so the
// store files are picked up automatically.
func (r *Result) WriteResult(root string) ([]string, error) {
	out := OutputPath(root, r.Env, r.App.App)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, fmt.Errorf("create output dir: %w", err)
	}
	data, err := r.HelmReleaseYAML()
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, data, 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", out, err)
	}
	written := []string{out}

	for _, s := range r.StoreReleases {
		sp := OutputPath(root, r.Env, s.FileStem)
		sdata, err := r.StoreReleaseYAML(s)
		if err != nil {
			return written, err
		}
		if err := os.WriteFile(sp, sdata, 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", sp, err)
		}
		written = append(written, sp)
	}
	return written, nil
}
