// Env scaffolding: generate a starter environments/<env>/cluster.yaml for a
// platform instance. This is what `idpctl init` writes so a fork does NOT have
// to hand-author a cluster.yaml (or, worse, copy someone else's homelab one with
// its IPs, module matrix, and registry orgs baked in).
//
// The output carries the fork's OWN identity — flux.repoURL/branch come from the
// caller (resolved from idp.yaml), never a default — and is heavily commented so
// the next steps (add zones for public routes, enable modules like keda, point
// the secret store) are discoverable. Every generated file is round-tripped
// through clusterenv parse+validate before return, so init can never emit a
// cluster.yaml that idpctl would later reject.
package scaffold

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/jakenesler/idp/internal/clusterenv"
	"sigs.k8s.io/yaml"
)

// EnvOptions drives `idpctl init`.
type EnvOptions struct {
	Env       string // environment name (dev|stage|prod or any). Required.
	RepoURL   string // flux.repoURL — the fork's platform repo. Required (instance identity).
	Branch    string // flux.branch (default "main").
	Backend   string // secrets backend: local|ssm. Default: dev=local, else ssm.
	StoreName string // secrets.storeRef.name. Default by backend.
}

// envView is the resolved template input (never exported).
type envView struct {
	Env, RepoURL, Branch, Backend, StoreName, PromoteFrom string
	MutableTags                                           bool
}

// GenerateEnv renders environments/<env>/cluster.yaml for one environment.
func GenerateEnv(o EnvOptions) (Files, error) {
	if o.Env == "" {
		return nil, fmt.Errorf("env is required")
	}
	if o.RepoURL == "" {
		return nil, fmt.Errorf("repoURL is required (the git URL of YOUR platform repo; set it in idp.yaml)")
	}
	v := envView{Env: o.Env, RepoURL: o.RepoURL, Branch: o.Branch, Backend: o.Backend, StoreName: o.StoreName}
	if v.Branch == "" {
		v.Branch = "main"
	}
	if v.Backend == "" {
		if o.Env == "prod" {
			v.Backend = "ssm"
		} else {
			v.Backend = "local"
		}
	}
	if v.Backend != "local" && v.Backend != "ssm" {
		return nil, fmt.Errorf("backend %q must be local or ssm", v.Backend)
	}
	if v.StoreName == "" {
		if v.Backend == "local" {
			v.StoreName = "platform-local"
		} else {
			v.StoreName = "platform-ssm"
		}
	}
	// dev iterates on mutable tags (:latest); promoted envs pin digests.
	v.MutableTags = o.Env == "dev"
	// Conventional promotion chain; a fork edits/removes promotion.from freely.
	switch o.Env {
	case "prod":
		v.PromoteFrom = "stage"
	case "stage":
		v.PromoteFrom = "dev"
	}

	data, err := renderEnv(v)
	if err != nil {
		return nil, err
	}
	// Fail-closed: never emit a cluster.yaml idpctl would reject. Mirror Load's
	// parse -> default -> validate without touching disk.
	var c clusterenv.Config
	if err := yaml.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("internal: generated cluster.yaml did not parse: %w", err)
	}
	if c.Env == "" {
		c.Env = o.Env
	}
	c.ApplyDefaults()
	if err := c.Validate(); err != nil {
		return nil, fmt.Errorf("internal: generated cluster.yaml failed validation: %w", err)
	}
	return Files{"environments/" + o.Env + "/cluster.yaml": data}, nil
}

func renderEnv(v envView) ([]byte, error) {
	t, err := template.New("env").Parse(envTmpl)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// envTmpl is the starter cluster.yaml. It is intentionally minimal-but-valid:
// LAN/in-cluster only (publicRoutes off so no zones are required), no infra
// modules enabled (so autoscale derives off — nothing to drive), and a generic
// secret store name. The comments point at the knobs a fork turns on next.
const envTmpl = `# environments/{{.Env}}/cluster.yaml — the {{.Env}} environment definition.
#
# Generated by ` + "`idpctl init`" + `. Parsed by internal/clusterenv. This is the
# per-environment contract: the secrets backend, the observability endpoints, the
# approved route zones, the seams this env provides, and the Flux wiring. Edit it
# to match YOUR cluster — the values below are safe, generic defaults.

env: {{.Env}}

# ── secrets backend ──────────────────────────────────────────────────────────
# local = external-secrets Kubernetes provider (or a plain in-cluster Secret) for
# dev; ssm = a cloud secret store (AWS SSM, etc.) for promoted envs. storeRef
# names the ClusterSecretStore the app charts point at — rename it to yours.
secrets:
  backend: {{.Backend}}
  storeRef:
    name: {{.StoreName}}
    kind: ClusterSecretStore
  refreshInterval: 1h
  # Registry pull secret (uncomment + point at your backend key once you have a
  # private registry credential stored there):
  # imagePull:
  #   secretName: ghcr-pull
  #   remoteKey: /path/in/your/secret/backend/dockerconfigjson
  #   storeRef: { name: {{.StoreName}}, kind: ClusterSecretStore }

# ── observability ────────────────────────────────────────────────────────────
# lokiURL is REQUIRED — it is injected into every app as Tier-A env. Point it at
# the log endpoint this cluster provides (the loki-stack chart's default below).
# otlpEndpoint is optional: declare it only when you actually run a collector.
observability:
  lokiURL: http://loki.loki.svc.cluster.local:3100
  consoleLogging: true

# ── approved route zones (host policy guardrail) ─────────────────────────────
# Public routes are validated against these host zones. Empty by default because
# this env ships with publicRoutes OFF (see seams). Add zones AND flip
# seams.publicRoutes to true once you have a public ingress (tunnel/ingress-nginx).
# zones:
#   - example.com
#   - "*.example.com"

# ── seams this env provides ──────────────────────────────────────────────────
# Declare ONLY what the cluster actually backs (validation + policy + ` + "`idpctl doctor`" + `
# enforce it). publicRoutes is off so a deploy.yaml public route is rejected
# until you provide ingress + zones. statefulStores/lanExpose/autoscale/volumes
# derive from the rest of this file (autoscale needs the keda module enabled).
seams:
  publicRoutes: false
{{- if .PromoteFrom}}

# ── promotion gate ───────────────────────────────────────────────────────────
# This env is promoted INTO from {{.PromoteFrom}} (idpctl promote --from {{.PromoteFrom}}).
promotion:
  from: {{.PromoteFrom}}
{{- end}}

# ── policy knobs ─────────────────────────────────────────────────────────────
{{- if .MutableTags}}
# dev tolerates mutable image tags (:latest) for fast iteration.
allowMutableTags: true
{{- else}}
# promoted envs pin immutable digests (never :latest).
allowMutableTags: false
{{- end}}
resourceBounds:
  maxCPU: "2"
  maxMemory: 2Gi

domain: svc.cluster.local

# ── Flux wiring (YOUR platform repo — instance identity) ──────────────────────
# repoURL/branch come from idp.yaml; they must point at the fork Flux syncs from.
flux:
  namespace: flux-system
  sourceName: flux-system
  repoURL: {{.RepoURL}}
  branch: {{.Branch}}

# ── module enable matrix ─────────────────────────────────────────────────────
# Shared infra installed into this cluster (keda, external-secrets, vpa, loki,
# image-builder, idp-shipper, …). None enabled by default. Enable what you need;
# chartRepo modules MUST pin source/chart/repoURL/version, localChart modules a
# chart path. Example (KEDA — required if any app declares autoscale):
# modules:
#   keda:
#     enabled: true
#     source: chartRepo
#     chart: keda
#     repoURL: https://kedacore.github.io/charts
#     version: 2.17.2
#     namespace: keda
modules: {}
`
